### ISSUE TITLE
Implement ability to place a ship on the board

### ISSUE THREAD

**Issue by taklae** [OSU-CS361-W17/group9_project1#3]
Card:
     - As a player, I want to be able to place ships on the game-board so that I can properly play the game.

     Conversation:
     - Ships can be placed anywhere inside the 10x10 board.
     - Orientation of the ships can be specified.

     Confirmation:
     - Test to make sure the ship won't be out of bounds
     - Test to make sure the ship won't overlap with another ship

**Comment by wsims** [comment]
Hunter should assign himself to this issue.
